services:
  discovery-server:
    image: discovery-server
    build:
      context: ./discovery-server
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8081:8080"
    expose:
      - "8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server

  product-service:
    build:
      context: ./product-service
    image: product-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      replicas: 2
    depends_on:
      - discovery-server
      - api-gateway

  order-service:
    build:
      context: ./order-service
    image: order-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      replicas: 2
    depends_on:
      - discovery-server
      - api-gateway