services:
  ecommerce-db:
    image: mysql
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8180:8080"
    expose:
      - "8180"
    depends_on:
      - discovery-server

  product-service:
    container_name: product-service
    image: product-service
    pull_policy: always
    depends_on:
      - discovery-server
      - api-gateway

  order-service:
    container_name: order-service
    image: order-service
    pull_policy: always
    depends_on:
      - discovery-server
      - api-gateway